apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: '1'
    deployment.kubernetes.io/max-replicas: '2'
    deployment.kubernetes.io/revision: '2'
  creationTimestamp: '2022-12-04T17:35:38Z'
  generation: 2
  labels:
    app: devops-argocd-test
    pod-template-hash: 7698cd7b86
  name: devops-argocd-test-7698cd7b86
  namespace: default
  ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: devops-argocd-test
      uid: d18eec60-33a6-4420-aa6a-155cd7480970
  resourceVersion: '4231829'
  uid: 35b4d43e-90be-4019-8b6b-3039bde01407
spec:
  minReadySeconds: 60
  replicas: 0
  selector:
    matchLabels:
      app: devops-argocd-test
      pod-template-hash: 7698cd7b86
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devops-argocd-test
        pod-template-hash: 7698cd7b86
    spec:
      containers:
        - image: 'registry.cn-hangzhou.aliyuncs.com/rookieops/argocd-test-app:v1'
          imagePullPolicy: Always
          name: devops-argocd-test
          ports:
            - containerPort: 8080
              name: tcp-8080
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 1000Mi
            requests:
              cpu: 10m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  observedGeneration: 2
  replicas: 0
