---
# Source: kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name:  mystack-kube-prometheus-st-admission-patch
  namespace: monitoring
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded   
  labels:
    app: kube-prometheus-stack-admission-patch    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: mystack
    app.kubernetes.io/version: "42.3.0"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-42.3.0
    release: "mystack"
    heritage: "Helm"
spec:
  template:
    metadata:
      name:  mystack-kube-prometheus-st-admission-patch
      labels:
        app: kube-prometheus-stack-admission-patch        
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: mystack
        app.kubernetes.io/version: "42.3.0"
        app.kubernetes.io/part-of: kube-prometheus-stack
        chart: kube-prometheus-stack-42.3.0
        release: "mystack"
        heritage: "Helm"
    spec:
      containers:
        - name: patch
          image: jettech/kube-webhook-certgen:v1.3.0
          imagePullPolicy: IfNotPresent
          args:
            - patch
            - --webhook-name=mystack-kube-prometheus-st-admission
            - --namespace=monitoring
            - --secret-name=mystack-kube-prometheus-st-admission
            - --patch-failure-policy=Fail
          securityContext:
          
            {}
          resources:
            {}
      restartPolicy: OnFailure
      serviceAccountName: mystack-kube-prometheus-st-admission
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
