---
# Source: prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name:  mystack-prometheus-operato-admission-create
  namespace: monitoring
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: prometheus-operator-admission-create    
    chart: prometheus-operator-9.3.2
    release: "mystack"
    heritage: "Helm"
spec:
  template:
    metadata:
      name:  mystack-prometheus-operato-admission-create
      labels:
        app: prometheus-operator-admission-create        
        chart: prometheus-operator-9.3.2
        release: "mystack"
        heritage: "Helm"
    spec:
      containers:
        - name: create
          image: jettech/kube-webhook-certgen:v1.2.1
          imagePullPolicy: IfNotPresent
          args:
            - create
            - --host=mystack-prometheus-operato-operator,mystack-prometheus-operato-operator.monitoring.svc
            - --namespace=monitoring
            - --secret-name=mystack-prometheus-operato-admission
          resources:
            {}
      restartPolicy: OnFailure
      serviceAccountName: mystack-prometheus-operato-admission
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
