---
# Source: prometheus-operator/templates/prometheus/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mystack-prometheus-operato-prometheus
  namespace: monitoring
  labels:
    app: prometheus-operator-prometheus
    
    chart: prometheus-operator-9.3.2
    release: "mystack"
    heritage: "Helm"
spec:
  selector:
    matchLabels:
      app: prometheus-operator-prometheus
      release: "mystack"
      self-monitor: "true"
  namespaceSelector:
    matchNames:
      - "monitoring"
  endpoints:
  - port: web
    path: "/metrics"
