---
# Source: kube-prometheus-stack/templates/prometheus/prometheus.yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: mystack-kube-prometheus-st-prometheus
  namespace: monitoring
  labels:
    app: kube-prometheus-stack-prometheus
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: mystack
    app.kubernetes.io/version: "42.3.0"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-42.3.0
    release: "mystack"
    heritage: "Helm"
spec:
  alerting:
    alertmanagers:
      - namespace: monitoring
        name: mystack-kube-prometheus-st-alertmanager
        port: http-web
        pathPrefix: "/"
        apiVersion: v2
  image: "quay.io/prometheus/prometheus:v2.39.1"
  version: v2.39.1
  externalUrl: http://mystack-kube-prometheus-st-prometheus.monitoring:9090
  paused: false
  replicas: 1
  shards: 1
  logLevel:  info
  logFormat:  logfmt
  listenLocal: false
  enableAdminAPI: false
  retention: "10d"
  walCompression: true
  routePrefix: "/"
  serviceAccountName: mystack-kube-prometheus-st-prometheus
  serviceMonitorSelector:
    matchLabels:
      release: "mystack"

  serviceMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: "mystack"

  podMonitorNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: "mystack"

  probeNamespaceSelector: {}
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      release: "mystack"

  portName: http-web
  hostNetwork: false
