---
# Source: prometheus-operator/templates/grafana/configmaps-datasources.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mystack-prometheus-operato-grafana-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
    app: prometheus-operator-grafana
    
    chart: prometheus-operator-9.3.2
    release: "mystack"
    heritage: "Helm"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://mystack-prometheus-operato-prometheus:9090/
      access: proxy
      isDefault: true
