---
# Source: prometheus-operator/templates/grafana/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mystack-prometheus-operato-grafana
  namespace: monitoring
  labels:
    app: prometheus-operator-grafana
    
    chart: prometheus-operator-9.3.2
    release: "mystack"
    heritage: "Helm"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/instance: "mystack"
  namespaceSelector:
    matchNames:
      - "monitoring"
  endpoints:
  - port: service
    path: "/metrics"
