---
# Source: prometheus/templates/pushgateway/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    component: "pushgateway"
    app: prometheus
    release: myprometheus
    chart: prometheus-15.10.0
    heritage: Helm
  name: myprometheus-pushgateway
rules:
  []
