---
# Source: kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: mystack-kube-prometheus-st-alertmanager
  namespace: monitoring
  labels:
    app: kube-prometheus-stack-alertmanager
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: mystack
    app.kubernetes.io/version: "42.3.0"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-42.3.0
    release: "mystack"
    heritage: "Helm"
spec:
  image: "quay.io/prometheus/alertmanager:v0.24.0"
  version: v0.24.0
  replicas: 1
  listenLocal: false
  serviceAccountName: mystack-kube-prometheus-st-alertmanager
  externalUrl: http://mystack-kube-prometheus-st-alertmanager.monitoring:9093
  paused: false
  logFormat: "logfmt"
  logLevel:  "info"
  retention: "120h"
  alertmanagerConfigSelector: {}
  alertmanagerConfigNamespaceSelector: {}
  routePrefix: "/"
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  portName: http-web
