---
# Source: prometheus-operator/templates/exporters/kube-scheduler/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mystack-prometheus-operato-kube-scheduler
  labels:
    app: prometheus-operator-kube-scheduler
    jobLabel: kube-scheduler
    
    chart: prometheus-operator-9.3.2
    release: "mystack"
    heritage: "Helm"
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 10251
      protocol: TCP
      targetPort: 10251
  selector:
    component: kube-scheduler
  type: ClusterIP
