prometheusOperator:
  admissionWebhooks:
    patch:
      image:
        registry: jettech
        repository: kube-webhook-certgen
        tag: v1.3.0

kube-state-metrics:
  image:
    repository: bitnami/kube-state-metrics
    tag: 2.7.0
    sha: ""
    pullPolicy: IfNotPresent


prometheus:
  service:
    ## Service type
    ##
    type: NodePort
    ## Port to expose on each node, if service type is NodePort
    ##
    nodePort: 30343

grafana:
  service:
    type: NodePort
    nodePort: 30344
