---
# Source: prometheus-operator/templates/exporters/kube-controller-manager/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mystack-prometheus-operato-kube-controller-manager
  labels:
    app: prometheus-operator-kube-controller-manager
    jobLabel: kube-controller-manager
    
    chart: prometheus-operator-9.3.2
    release: "mystack"
    heritage: "Helm"
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 10252
      protocol: TCP
      targetPort: 10252
  selector:
    component: kube-controller-manager
  type: ClusterIP
