---
# Source: prometheus/templates/alertmanager/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "alertmanager"
    app: prometheus
    release: myprometheus
    chart: prometheus-15.10.0
    heritage: Helm
  name: myprometheus-alertmanager
  namespace: monitoring
  annotations:
    {}
