---
# Source: prometheus-operator/templates/alertmanager/alertmanager.yaml
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: mystack-prometheus-operato-alertmanager
  namespace: monitoring
  labels:
    app: prometheus-operator-alertmanager
    
    chart: prometheus-operator-9.3.2
    release: "mystack"
    heritage: "Helm"
spec:
  baseImage: quay.io/prometheus/alertmanager
  version: v0.21.0
  replicas: 1
  listenLocal: false
  serviceAccountName: mystack-prometheus-operato-alertmanager
  externalUrl: http://mystack-prometheus-operato-alertmanager.monitoring:9093
  paused: false
  logFormat: "logfmt"
  logLevel:  "info"
  retention: "120h"
  routePrefix: "/"
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  portName: web
