---
# Source: prometheus-operator/templates/alertmanager/psp-role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mystack-prometheus-operato-alertmanager
  namespace: monitoring
  labels:
    app: prometheus-operator-alertmanager
    
    chart: prometheus-operator-9.3.2
    release: "mystack"
    heritage: "Helm"
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - mystack-prometheus-operato-alertmanager
