---
# Source: postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgresql1
  namespace: "nsdb"
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-12.0.0
    app.kubernetes.io/instance: postgresql1
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  postgres-password: "cGFzc3dkeHh4eA=="
  password: "YWRtaW4="
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
