---
# Source: kube-prometheus-stack/charts/grafana/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mystack-grafana-clusterrolebinding
  labels:
    helm.sh/chart: grafana-6.47.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: mystack
    app.kubernetes.io/version: "9.3.0"
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: mystack-grafana
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: mystack-grafana-clusterrole
  apiGroup: rbac.authorization.k8s.io
