---
# Source: kube-prometheus-stack/charts/grafana/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mystack-grafana
  namespace: monitoring
  labels:
    helm.sh/chart: grafana-6.47.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: mystack
    app.kubernetes.io/version: "9.3.0"
    app.kubernetes.io/managed-by: Helm
rules: []
