---
# Source: kube-prometheus-stack/charts/grafana/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mystack-grafana
  namespace: monitoring
  labels:
    helm.sh/chart: grafana-6.47.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: mystack
    app.kubernetes.io/version: "9.3.0"
    app.kubernetes.io/managed-by: Helm
spec:
  endpoints:
  - port: http-web
    scrapeTimeout: 30s
    honorLabels: true
    path: /metrics
    scheme: http
  jobLabel: "mystack"
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/instance: mystack
  namespaceSelector:
    matchNames:
      - monitoring
