---
# Source: terraboard/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-terraboard
  labels:
    app.kubernetes.io/name: terraboard
    helm.sh/chart: terraboard-2.2.4
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: terraboard
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: terraboard
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: release-name-terraboard
      securityContext:
        {}
      containers:
        - name: terraboard
          securityContext:
            {}
          image: "docker.io/camptocamp/terraboard:2.2.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: swagger
              containerPort: 8081
              protocol: TCP
          env:
            - name: TERRABOARD_BASE_URL
              value: /
            - name: TERRABOARD_PORT
              value: "8080"
            - name: TERRABOARD_SWAGGER_PORT
              value: "8081"
            - name: DB_HOST
              value: release-name-terraboard-db
            - name: DB_SSLMODE
              value: 
            - name: DB_NAME
              value: db1
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: release-name-terraboard
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: release-name-terraboard
                  key: DB_PASSWORD

            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: release-name-terraboard
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: release-name-terraboard
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              value: 
            - name: AWS_BUCKET
              value: 
            - name: AWS_DYNAMODB_TABLE
              value: 
            - name: AWS_FILE_EXTENSION
              value: 

#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          resources:
            {}
      volumes:
        - name: secrets
          secret:
            secretName: release-name-terraboard
