---
# Source: terraboard/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-terraboard
  labels:
    app.kubernetes.io/name: terraboard
    helm.sh/chart: terraboard-2.2.4
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/managed-by: Helm
stringData:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  DB_USER: "myuserAAA"
  DB_PASSWORD: "mypasswdAAA"
