---
# Source: terraboard/templates/service-db.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-terraboard-db
  labels:
    app.kubernetes.io/name: terraboard
    helm.sh/chart: terraboard-2.2.4
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: terraboard-db
    app.kubernetes.io/instance: release-name
