---
# Source: terraboard/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-terraboard
  labels:
    app.kubernetes.io/name: terraboard
    helm.sh/chart: terraboard-2.2.4
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
      nodePort:  30387
  selector:
    app.kubernetes.io/name: terraboard
    app.kubernetes.io/instance: release-name
