---
# Source: terraboard/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-terraboard
  labels:
    app.kubernetes.io/name: terraboard
    helm.sh/chart: terraboard-2.2.4
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/managed-by: Helm
