---
# Source: terraboard/templates/service-swagger.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-terraboard-swagger
  labels:
    app.kubernetes.io/name: terraboard
    helm.sh/chart: terraboard-2.2.4
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: terraboard
    app.kubernetes.io/instance: release-name
