---
# Source: myapp8-helm/templates/app8.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp8-pro-name
  name: myapp8-pro-name
spec:
  ports:
    - name: tcpaa-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30392
  selector:
    app: myapp8-pro-name
  sessionAffinity: None
  type: NodePort
---
# Source: myapp8-helm/templates/app8.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp8-pro-name
  name: myapp8-pro-name
spec:
  minReadySeconds: 60
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: myapp8-pro-name
  template:
    metadata:
      labels:
        app: myapp8-pro-name
    spec:
      containers:
        - name: myapp8-pro-name
          image:  registry.cn-hangzhou.aliyuncs.com/rookieops/argocd-test-app:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: tcpaa-8080
              protocol: TCP
          resources:
            requests:
              cpu:  17m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
