---
# Source: grafana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mygrafana
  namespace: monitoring
  labels:
    helm.sh/chart: grafana-6.38.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: mygrafana
    app.kubernetes.io/version: "9.1.4"
    app.kubernetes.io/managed-by: Helm
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain =
