---
# Source: grafana/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mygrafana
  namespace: monitoring
  labels:
    helm.sh/chart: grafana-6.38.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: mygrafana
    app.kubernetes.io/version: "9.1.4"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - name: service
      port: 80
      protocol: TCP
      targetPort: 3000
      nodePort: 30344
      
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: mygrafana
