apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "terraboard.fullname" . }}-db
  labels:
    app.kubernetes.io/name: {{ include "terraboard.name" . }}-db
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  serviceName: headless-{{ include "terraboard.name" . }}-db
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "terraboard.name" . }}-db
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "terraboard.name" . }}-db
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
￼   {{- end }}
      containers:
        - name: {{ .Chart.Name }}-db
          image: "{{ .Values.dbimage.repository }}:{{ .Values.dbimage.tag }}"
          imagePullPolicy: {{ .Values.dbimage.pullPolicy }}
          env:
            - name: POSTGRES_DB
              value: "db1"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "terraboard.fullname" . }}
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "terraboard.fullname" . }}
                  key: DB_PASSWORD
