apiVersion: v1
kind: Service
metadata:
  name: {{ include "terraboard.fullname" . }}-db
  labels:
{{ include "terraboard.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "terraboard.name" . }}-db
    app.kubernetes.io/instance: {{ .Release.Name }}
