apiVersion: v1
kind: Service
metadata:
  name: {{ include "terraboard.fullname" . }}-db
  labels:
{{ include "terraboard.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
{{- if .Values.service.nodePort }}
      nodePort:  {{ .Values.service.nodePort }}
{{- end }}
  selector:
    app.kubernetes.io/name: {{ include "terraboard.name" . }}-db
    app.kubernetes.io/instance: {{ .Release.Name }}
