apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops-argocd-app6
  name: devops-argocd-app6
  namespace: default
spec:
  minReadySeconds: 60
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: devops-argocd-app6
  template:
    metadata:
      labels:
        app: devops-argocd-app6
    spec:
      containers:
        - name: devops-argocd-app6
          image: registry.cn-hangzhou.aliyuncs.com/rookieops/argocd-test-app:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: tcp-8080
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devops-argocd-app6
  name: devops-argocd-app6
  namespace: default
spec:
  ports:
    - name: tcp-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30381
  selector:
    app: devops-argocd-app6
  sessionAffinity: None
  type: NodePort

