---
# Source: prometheus/templates/server/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: "server"
    app: prometheus
    release: myprometheus
    chart: prometheus-15.10.0
    heritage: Helm
  name: myprometheus-server
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "nfs-client"
  resources:
    requests:
      storage: "8Gi"
