---
# Source: prometheus-operator/charts/prometheus-node-exporter/templates/psp-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psp-mystack-prometheus-node-exporter
  labels:     
    app: prometheus-node-exporter
    heritage: Helm
    release: mystack
    chart: prometheus-node-exporter-1.10.0
    jobLabel: node-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp-mystack-prometheus-node-exporter
subjects:
  - kind: ServiceAccount
    name: mystack-prometheus-node-exporter
    namespace: monitoring
