---
# Source: prometheus-operator/charts/prometheus-node-exporter/templates/psp-clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp-mystack-prometheus-node-exporter
  labels:     
    app: prometheus-node-exporter
    heritage: Helm
    release: mystack
    chart: prometheus-node-exporter-1.10.0
    jobLabel: node-exporter
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - mystack-prometheus-node-exporter
