---
# Source: prometheus-operator/charts/prometheus-node-exporter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mystack-prometheus-node-exporter
  namespace: monitoring
  labels:
    app: prometheus-node-exporter
    chart: prometheus-node-exporter-1.10.0
    release: "mystack"
    heritage: "Helm"
imagePullSecrets:
  []
