---
# Source: prometheus-operator/templates/exporters/node-exporter/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mystack-prometheus-operato-node-exporter
  namespace: monitoring
  labels:
    app: prometheus-operator-node-exporter
    
    chart: prometheus-operator-9.3.2
    release: "mystack"
    heritage: "Helm"
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
      app: prometheus-node-exporter
      release: mystack
  endpoints:
  - port: metrics
