---
# Source: prometheus-operator/templates/exporters/core-dns/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mystack-prometheus-operato-coredns
  labels:
    app: prometheus-operator-coredns
    jobLabel: coredns
    
    chart: prometheus-operator-9.3.2
    release: "mystack"
    heritage: "Helm"
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 9153
      protocol: TCP
      targetPort: 9153
  selector:
    k8s-app: kube-dns
