---
# Source: prometheus-operator/charts/grafana/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mystack-grafana
  namespace: monitoring
  labels:
    helm.sh/chart: grafana-5.3.6
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: mystack
    app.kubernetes.io/version: "7.0.5"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  admin-user: "YWRtaW4="
  admin-password: "cHJvbS1vcGVyYXRvcg=="
  ldap-toml: ""
