---
# Source: prometheus-operator/charts/grafana/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mystack-grafana
  namespace: monitoring
  labels:
    helm.sh/chart: grafana-5.3.6
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: mystack
    app.kubernetes.io/version: "7.0.5"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: service
      port: 80
      protocol: TCP
      targetPort: 3000

  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: mystack
