---
# Source: prometheus-operator/templates/exporters/kube-etcd/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mystack-prometheus-operato-kube-etcd
  namespace: monitoring
  labels:
    app: prometheus-operator-kube-etcd
    
    chart: prometheus-operator-9.3.2
    release: "mystack"
    heritage: "Helm"
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
      app: prometheus-operator-kube-etcd
      release: "mystack"
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
  - port: http-metrics
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
